name: SpecAISeg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy==1.22.3
  - boost-cpp==1.74.0
  - dill==0.3.5.1
  - defusedxml==0.7.1
  - ipython_genutils==0.2.0
  - font-ttf-ubuntu==0.83
  - libvorbis==1.3.7
  - mkl_fft==1.3.1
  - libxkbcommon==1.0.3
  - openh264==2.1.1
  - pytorch-mutex==1.0
  - sip==4.19.13
  - certifi==2022.6.15
  - mkl_random==1.2.2
  - numpy-base==1.22.3
  - tornado==6.1
  - glib-tools==2.70.2
  - gtk3==3.24.33
  - libgfortran5==12.1.0
  - pytorch==1.12.0
  - nbconvert-core==6.5.0
  - mysql-common==8.0.29
  - jsonschema==4.6.0
  - libzlib==1.2.12
  - jupyter_console==6.4.3
  - fonts-conda-ecosystem==1
  - gettext==0.19.8.1
  - jupyter_client==7.3.4
  - libglib==2.70.2
  - mkl==2021.4.0
  - xorg-libsm==1.2.3
  - xorg-fixesproto==5.0
  - xorg-renderproto==0.11.1
  - pywavelets==1.3.0
  - libxcb==1.13
  - mistune==0.8.4
  - alsa-lib==1.2.3.2
  - typing_extensions==4.2.0
  - icu==69.1
  - openssl==3.0.5
  - pyqt5-sip==4.19.18
  - zfp==0.5.5
  - prometheus_client==0.14.1
  - cairomm-1.0==1.12.2
  - libcblas==3.9.0
  - cloudpickle==2.1.0
  - font-ttf-dejavu-sans-mono==2.37
  - gmp==6.2.1
  - prompt_toolkit==3.0.29
  - giflib==5.2.1
  - sigcpp-2.0==2.10.7
  - dask-core==2022.5.2
  - threadpoolctl==3.1.0
  - libaec==1.0.6
  - libopus==1.3.1
  - libstdcxx-ng==12.1.0
  - python-fastjsonschema==2.15.3
  - libsodium==1.0.18
  - argon2-cffi==21.3.0
  - krb5==1.19.3
  - libgcc-ng==12.1.0
  - pickleshare==0.7.5
  - terminado==0.15.0
  - libssh2==1.10.0
  - pygments==2.12.0
  - pcre==8.45
  - pycparser==2.21
  - networkx==2.8.3
  - pip==22.1.2
  - graph-tool==2.45
  - zlib==1.2.12
  - matplotlib-base==3.5.2
  - qtpy==2.1.0
  - fonttools==4.33.3
  - libdeflate==1.10
  - pyqt==5.12.3
  - ca-certificates==2022.6.15
  - libgirepository==1.72.0
  - libzopfli==1.0.3
  - gstreamer==1.20.2
  - c-ares==1.18.1
  - libogg==1.3.4
  - attrs==21.4.0
  - backports==1.0
  - nbconvert-pandoc==6.5.0
  - nbclient==0.6.4
  - tbb==2021.5.0
  - jedi==0.18.1
  - readline==8.1
  - blas==1.0
  - mkl-service==2.4.0
  - flit-core==3.7.1
  - libpq==14.3
  - pygobject==3.42.1
  - xorg-xextproto==7.3.0
  - brotli-bin==1.0.9
  - lerc==3.0
  - matplotlib-inline==0.1.3
  - libcups==2.3.3
  - atk-1.0==2.36.0
  - entrypoints==0.4
  - pyyaml==6.0
  - jupyter_core==4.10.0
  - cfitsio==4.1.0
  - cairo==1.16.0
  - gst-plugins-base==1.20.2
  - ld_impl_linux-64==2.36.1
  - psutil==5.9.1
  - epoxy==1.5.10
  - xorg-libxau==1.0.9
  - xorg-libxdmcp==1.1.3
  - boost==1.74.0
  - decorator==5.1.1
  - nest-asyncio==1.5.5
  - asttokens==2.0.5
  - tqdm==4.64.0
  - pyqtchart==5.12
  - xorg-xproto==7.0.31
  - jinja2==3.1.2
  - xorg-kbproto==1.0.7
  - stack_data==0.2.0
  - ffmpeg==4.3
  - harfbuzz==4.2.0
  - scipy==1.8.1
  - qtconsole-base==5.3.1
  - cairomm==1.12.2
  - torchvision==0.13.0
  - xorg-libxtst==1.2.3
  - jxrlib==1.1
  - libedit==3.1.20191231
  - pox==0.3.1
  - python==3.10.4
  - imagecodecs==2022.2.22
  - libgfortran-ng==12.1.0
  - multiprocess==0.70.13
  - ipython==8.4.0
  - libnsl==2.0.0
  - notebook==6.4.12
  - widgetsnbextension==3.6.0
  - _libgcc_mutex==0.1
  - python_abi==3.10
  - sqlite==3.38.5
  - locket==1.0.0
  - hicolor-icon-theme==0.17
  - debugpy==1.6.0
  - pillow==9.1.1
  - cytoolz==0.11.2
  - libbrotlienc==1.0.9
  - pyqt-impl==5.12.3
  - parso==0.8.3
  - scikit-image==0.19.2
  - zlib-ng==2.0.6
  - libllvm13==13.0.1
  - argon2-cffi-bindings==21.2.0
  - prompt-toolkit==3.0.29
  - libbrotlidec==1.0.9
  - six==1.16.0
  - snappy==1.1.9
  - openjpeg==2.4.0
  - qtconsole==5.3.1
  - libclang==13.0.1
  - send2trash==1.8.0
  - zipp==3.8.0
  - pexpect==4.8.0
  - unicodedata2==14.0.0
  - colorama==0.4.4
  - xorg-recordproto==1.14.2
  - lcms2==2.12
  - importlib_resources==5.7.1
  - pyqtwebengine==5.12.1
  - libpng==1.6.37
  - xorg-inputproto==2.3.2
  - xorg-libx11==1.7.2
  - charls==2.3.4
  - idna==3.3
  - cryptography==37.0.1
  - pycairo==1.21.0
  - xorg-libxrender==0.9.10
  - ptyprocess==0.7.0
  - tinycss2==1.1.1
  - libblas==3.9.0
  - jpeg==9e
  - libwebp==1.2.2
  - zstd==1.5.2
  - lz4-c==1.9.3
  - pysocks==1.7.1
  - zeromq==4.3.4
  - pthread-stubs==0.4
  - at-spi2-atk==2.38.0
  - ppft==1.7.6.5
  - wheel==0.37.1
  - tifffile==2022.5.4
  - font-ttf-inconsolata==3.000
  - keyutils==1.6.1
  - cffi==1.15.0
  - libcurl==7.83.1
  - executing==0.8.3
  - libiconv==1.16
  - sparsehash==2.0.4
  - freetype==2.10.4
  - jupyterlab_widgets==1.1.0
  - ncurses==6.3
  - aom==3.3.0
  - pyopenssl==22.0.0
  - libtiff==4.4.0
  - librsvg==2.52.5
  - backports.functools_lru_cache==1.6.4
  - liblapack==3.9.0
  - beautifulsoup4==4.11.1
  - pyzmq==23.1.0
  - at-spi2-core==2.40.3
  - libevent==2.1.10
  - nss==3.78
  - pyparsing==3.0.9
  - pixman==0.40.0
  - brunsli==0.1
  - fsspec==2022.5.0
  - tk==8.6.12
  - importlib-metadata==4.11.4
  - typing-extensions==4.2.0
  - qt==5.12.9
  - bleach==5.0.0
  - llvm-openmp==14.0.4
  - cudatoolkit==10.2.89
  - _openmp_mutex==4.5
  - brotlipy==0.7.0
  - libbrotlicommon==1.0.9
  - gnutls==3.6.13
  - fribidi==1.0.10
  - kiwisolver==1.4.2
  - libffi==3.4.2
  - nbconvert==6.5.0
  - pango==1.50.7
  - fonts-conda-forge==1
  - mysql-libs==8.0.29
  - xorg-libxfixes==5.0.3
  - expat==2.4.8
  - ipykernel==6.13.1
  - jupyterlab_pygments==0.2.2
  - setuptools==62.3.3
  - soupsieve==2.3.1
  - cycler==0.11.0
  - libxml2==2.9.12
  - blosc==1.21.1
  - ipywidgets==7.7.0
  - xorg-libice==1.0.10
  - jupyter==1.0.0
  - libuuid==2.32.1
  - zstandard==0.17.0
  - gdk-pixbuf==2.42.8
  - libavif==0.10.1
  - munkres==1.1.4
  - dbus==1.13.6
  - imageio==2.19.3
  - backcall==0.2.0
  - pure_eval==0.2.2
  - toolz==0.11.2
  - xorg-libxi==1.7.10
  - partd==1.2.0
  - nspr==4.32
  - torchaudio==0.12.0
  - xz==5.2.5
  - libnghttp2==1.47.0
  - graphite2==1.3.13
  - font-ttf-source-code-pro==2.038
  - pandoc==2.18
  - yaml==0.2.5
  - pyrsistent==0.18.1
  - pandocfilters==1.5.0
  - tzdata==2022a
  - pathos==0.2.9
  - python-dateutil==2.8.2
  - markupsafe==2.1.1
  - cython==0.29.28
  - brotli==1.0.9
  - future==0.18.2
  - fontconfig==2.14.0
  - libwebp-base==1.2.2
  - nettle==3.6
  - ninja==1.11.0
  - nbformat==5.4.0
  - webencodings==0.5.1
  - bzip2==1.0.8
  - xorg-libxext==1.3.4
  - glib==2.70.2
  - libev==4.33
  - packaging==21.3
  - traitlets==5.2.2.post1
  - wcwidth==0.2.5
  - lame==3.100
  - graph-tool-base==2.45
  - c-blosc2==2.1.1